# Generated by Django 6.0.5 on 2026-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
